interface Env {
    UPSTASH_REDIS_REST_URL: string;
    UPSTASH_REDIS_REST_TOKEN: string;
    UPSTASH_REDIS_RATE_LIMIT_VIRGINIA_REST_URL: string;
    UPSTASH_REDIS_RATE_LIMIT_VIRGINIA_REST_TOKEN: string;
    UPSTASH_REDIS_RATE_LIMIT_CALIFORNIA_REST_URL: string;
    UPSTASH_REDIS_RATE_LIMIT_CALIFORNIA_REST_TOKEN: string;
    UPSTASH_REDIS_RATE_LIMIT_GERMANY_REST_URL: string;
    UPSTASH_REDIS_RATE_LIMIT_GERMANY_REST_TOKEN: string;
    UPSTASH_REDIS_RATE_LIMIT_JAPAN_REST_URL: string;
    UPSTASH_REDIS_RATE_LIMIT_JAPAN_REST_TOKEN: string;
    UPSTASH_REDIS_RATE_LIMIT_AUSTRALIA_REST_URL: string;
    UPSTASH_REDIS_RATE_LIMIT_AUSTRALIA_REST_TOKEN: string;
    UPSTASH_REDIS_RATE_LIMIT_BRAZIL_REST_URL: string;
    UPSTASH_REDIS_RATE_LIMIT_BRAZIL_REST_TOKEN: string;
    UPSTASH_REDIS_RATE_LIMIT_INDIA_REST_URL: string;
    UPSTASH_REDIS_RATE_LIMIT_INDIA_REST_TOKEN: string;
    UPSTASH_REDIS_RATE_LIMIT_SINGAPORE_REST_URL: string;
    UPSTASH_REDIS_RATE_LIMIT_SINGAPORE_REST_TOKEN: string;
}
